-- AlterTable
ALTER TABLE `orders` ADD COLUMN `selection_confirmed_at` DATETIME(3) NULL,
    MODIFY `status` ENUM('PENDING_CONFIRMATION', 'WAITING_MAKEUP', 'MAKEUP_IN_PROGRESS', 'WAITING_PHOTOGRAPHY', 'PHOTOGRAPHY_IN_PROGRESS', 'WAITING_SELECTION', 'WAITING_RETOUCH', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'PENDING_CONFIRMATION';
