<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { ElMessage } from 'element-plus';
import api,{errorMessage} from '@/api/http';
import type { Order, Store } from '@/types';

const route=useRoute(),router=useRouter(),loading=ref(true),saving=ref(false);
const merchant=reactive({name:'',merchantCode:String(route.params.merchantCode),stores:[] as Store[]});
const form=reactive({customerName:'',customerPhone:'',storeId:'',packageName:'',appointmentAt:'',notes:''});
async function load(){try{Object.assign(merchant,(await api.get(`/client/merchants/${merchant.merchantCode}`)).data);form.storeId=merchant.stores[0]?.id??''}catch(e){ElMessage.error(errorMessage(e))}finally{loading.value=false}}
async function submit(){if(!form.customerName||!form.customerPhone||!form.storeId){ElMessage.warning('请完整填写姓名、手机号和门店');return}saving.value=true;try{const payload={...form,merchantCode:merchant.merchantCode,appointmentAt:form.appointmentAt||undefined,packageName:form.packageName||undefined,notes:form.notes||undefined};const order=(await api.post<Order>('/client/orders',payload)).data;ElMessage.success('订单创建成功，等待门店确认');await router.replace(`/client/order/${order.accessToken}`)}catch(e){ElMessage.error(errorMessage(e))}finally{saving.value=false}}
onMounted(load);
</script>
<template><div class="client-page"><header class="client-brand"><span>旅</span><div><b>{{merchant.name||'旅拍管家'}}</b><small>微信客户服务 · 扫码建单</small></div></header><main v-loading="loading"><section class="welcome"><em>开启美好旅拍</em><h1>填写预约资料</h1><p>提交后门店将确认订单，并安排化妆和摄影服务。</p></section><section class="client-card"><el-form label-position="top"><el-form-item label="您的姓名" required><el-input v-model="form.customerName" size="large" placeholder="请输入姓名"/></el-form-item><el-form-item label="手机号码" required><el-input v-model="form.customerPhone" size="large" inputmode="tel" placeholder="用于门店联系您"/></el-form-item><el-form-item label="服务门店" required><el-select v-model="form.storeId" size="large" style="width:100%"><el-option v-for="s in merchant.stores" :key="s.id" :label="s.name" :value="s.id"><span>{{s.name}}</span><small style="float:right;color:#999">{{s.address}}</small></el-option></el-select></el-form-item><el-form-item label="期望拍摄时间"><el-date-picker v-model="form.appointmentAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" size="large" style="width:100%"/></el-form-item><el-form-item label="套餐或拍摄需求"><el-input v-model="form.packageName" size="large" placeholder="如：草原旅拍双人套餐"/></el-form-item><el-form-item label="补充说明"><el-input v-model="form.notes" type="textarea" :rows="3" placeholder="服装尺码、风格偏好等"/></el-form-item><el-button type="primary" size="large" :loading="saving" class="submit" @click="submit">提交并创建订单</el-button></el-form></section><p class="safe">资料仅用于本次旅拍服务</p></main></div></template>
<style scoped>.client-page{position:fixed;inset:0;overflow:auto;z-index:100;background:linear-gradient(180deg,#edf5f1 0,#f7f8f8 280px);color:#20362f}.client-brand{height:70px;padding:0 20px;display:flex;align-items:center;gap:10px;background:rgba(255,255,255,.8);backdrop-filter:blur(12px)}.client-brand>span{width:36px;height:36px;border-radius:10px;background:#315c4e;color:#efcd7c;display:grid;place-items:center;font-family:serif}.client-brand div{display:flex;flex-direction:column}.client-brand b{font-size:15px}.client-brand small{font-size:10px;color:#87938e;margin-top:2px}.client-page main{max-width:520px;margin:auto;padding:30px 18px}.welcome em{font-style:normal;color:#a6803d;font-size:12px}.welcome h1{font-size:28px;margin:8px 0}.welcome p{color:#718079;font-size:13px;margin-bottom:24px}.client-card{background:#fff;border-radius:18px;padding:22px 20px;box-shadow:0 12px 32px rgba(35,70,57,.08)}.submit{width:100%;height:48px;margin-top:8px}.safe{text-align:center;color:#a0aaa5;font-size:11px;margin:20px}</style>
