<script setup lang="ts">
import { computed, onMounted } from 'vue';
import { useAuthStore } from '@/stores/auth';
const auth=useAuthStore(); onMounted(()=>auth.loadProfile());
const planName=computed(()=>({TRIAL:'试用版',BASIC:'基础版',PROFESSIONAL:'专业版',ENTERPRISE:'企业版'}[auth.profile?.merchant?.plan ?? ''] ?? '-'));
const expire=computed(()=>auth.profile?.merchant?.expireAt ? new Date(auth.profile.merchant.expireAt).toLocaleDateString('zh-CN') : '长期有效');
</script>
<template><div class="page">
  <div class="welcome"><div><span>{{ new Date().getHours()<12?'上午好':'欢迎回来' }}</span><h1>{{ auth.profile?.employee?.name || auth.profile?.username }}，今天也要记录美好</h1><p>这里是你当前商家的经营概览。</p></div><div class="date">{{ new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'}) }}</div></div>
  <section class="merchant-card"><div class="merchant-logo">旅</div><div class="merchant-info"><span>当前商家</span><h2>{{ auth.profile?.merchant?.name }}</h2><p><i>专业认证</i> 商户数据安全隔离中</p></div><div class="plan"><span>套餐版本</span><b>{{ planName }}</b><small>有效期至 {{ expire }}</small></div></section>
  <div class="section-title"><h3>基础数据</h3><span>实时更新</span></div>
  <section class="stats"><router-link to="/stores"><i class="green">▦</i><div><span>门店数量</span><b>{{ auth.profile?.stats.storeCount ?? 0 }}</b><small>家门店</small></div><em>→</em></router-link><router-link to="/employees"><i class="gold">♙</i><div><span>员工数量</span><b>{{ auth.profile?.stats.employeeCount ?? 0 }}</b><small>位员工</small></div><em>→</em></router-link><article><i class="blue">✓</i><div><span>系统状态</span><b class="healthy">运行正常</b><small>所有服务可用</small></div></article></section>
  <div class="section-title"><h3>业务概览</h3><span>第二阶段开放</span></div><section class="future"><div v-for="item in ['今日订单','今日收款','待拍摄','待修图','待交付','售后']" :key="item"><span>{{ item }}</span><b>—</b><small>即将上线</small></div></section>
</div></template>
<style scoped>
.welcome{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:24px}.welcome>div>span{font-size:13px;color:#ad8b46}.welcome h1{font-size:25px;margin:8px 0 6px}.welcome p{color:#8791a0;margin:0;font-size:13px}.date{color:#8993a1;font-size:13px;margin-top:10px}.merchant-card{height:146px;background:#284f43;color:#fff;border-radius:15px;padding:27px 30px;display:flex;align-items:center;box-shadow:0 7px 25px rgba(35,77,65,.13);position:relative;overflow:hidden}.merchant-card::after{content:"旅";position:absolute;right:190px;top:-58px;font:190px serif;color:rgba(255,255,255,.025)}.merchant-logo{width:72px;height:72px;border-radius:14px;background:#e7c477;color:#315c4e;display:grid;place-items:center;font:700 30px serif;margin-right:20px}.merchant-info>span,.plan span{font-size:11px;color:rgba(255,255,255,.6)}.merchant-info h2{margin:7px 0;font-size:21px}.merchant-info p{margin:0;font-size:11px;color:rgba(255,255,255,.65)}.merchant-info i{font-style:normal;color:#eccf8e;margin-right:8px}.plan{margin-left:auto;padding:4px 50px 4px 60px;border-left:1px solid rgba(255,255,255,.13);display:flex;flex-direction:column}.plan b{font-size:20px;color:#f0d18d;margin:7px 0}.plan small{font-size:11px;color:rgba(255,255,255,.55)}.section-title{display:flex;align-items:center;margin:27px 0 14px}.section-title h3{margin:0;font-size:16px}.section-title span{margin-left:12px;font-size:11px;color:#a3aab5}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.stats>a,.stats article{height:121px;background:#fff;border:1px solid #e7eaef;border-radius:13px;padding:23px;display:flex;align-items:center;text-decoration:none;color:inherit}.stats i{width:48px;height:48px;border-radius:12px;display:grid;place-items:center;font-style:normal;font-size:21px;margin-right:16px}.green{background:#e7f1ed;color:#397663}.gold{background:#fbf2df;color:#b68939}.blue{background:#e9f0f7;color:#4e78a2}.stats div{display:grid;grid-template-columns:auto auto;align-items:baseline}.stats div span{grid-column:1/3;color:#8993a1;font-size:12px}.stats b{font-size:27px;margin-top:8px}.stats small{font-size:11px;color:#9da5b0;margin-left:6px}.stats em{font-style:normal;color:#a4abb5;margin-left:auto}.stats b.healthy{font-size:17px;color:#3c8a69}.future{display:grid;grid-template-columns:repeat(6,1fr);background:#fff;border:1px solid #e7eaef;border-radius:13px}.future div{padding:20px;border-right:1px solid #edf0f3;display:flex;flex-direction:column}.future div:last-child{border:0}.future span{font-size:12px;color:#8993a1}.future b{font-size:22px;margin:12px 0;color:#adb3bc}.future small{font-size:10px;color:#b1b7c0}
</style>
