<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import api,{errorMessage} from '@/api/http'; import type{Employee,Paged,RoleCode,Store}from '@/types';
const roleLabels:Record<RoleCode,string>={SUPER_ADMIN:'平台管理员',OWNER:'老板',MANAGER:'店长',RECEPTION:'前台',SALES:'销售',MAKEUP:'化妆师',PHOTOGRAPHER:'摄影师',RETOUCHER:'修图师'};
const roles=(['MANAGER','RECEPTION','SALES','MAKEUP','PHOTOGRAPHER','RETOUCHER'] as RoleCode[]);const loading=ref(false),dialog=ref(false),saving=ref(false),editingId=ref('');
const query=reactive({keyword:'',role:'',storeId:'',page:1,pageSize:10});const result=reactive<Paged<Employee>>({items:[],total:0,page:1,pageSize:10});const stores=ref<Store[]>([]);
const form=reactive({name:'',phone:'',storeId:'',role:'PHOTOGRAPHER' as RoleCode,status:'ACTIVE',joinDate:''});
async function load(){loading.value=true;const params=Object.fromEntries(Object.entries(query).filter(([,value])=>value!==''));try{Object.assign(result,(await api.get<Paged<Employee>>('/employees',{params})).data)}catch(e){ElMessage.error(errorMessage(e))}finally{loading.value=false}}
async function loadStores(){stores.value=(await api.get<Paged<Store>>('/stores',{params:{pageSize:100,status:'ACTIVE'}})).data.items}
function open(item?:Employee){editingId.value=item?.id??'';Object.assign(form,{name:item?.name??'',phone:item?.phone??'',storeId:item?.storeId??'',role:item?.role??'PHOTOGRAPHER',status:item?.status??'ACTIVE',joinDate:item?.joinDate?.slice(0,10)??''});dialog.value=true}
async function save(){if(!form.name||!form.phone){ElMessage.warning('请填写姓名和手机号');return}saving.value=true;const payload={...form,storeId:form.storeId||undefined,joinDate:form.joinDate||undefined};try{if(editingId.value){await api.patch(`/employees/${editingId.value}`,payload)}else{await api.post('/employees',payload)}ElMessage.success('保存成功');dialog.value=false;await load()}catch(e){ElMessage.error(errorMessage(e))}finally{saving.value=false}}
async function remove(item:Employee){await ElMessageBox.confirm(`确认删除员工“${item.name}”？`,'删除员工',{type:'warning'});try{await api.delete(`/employees/${item.id}`);ElMessage.success('已删除');await load()}catch(e){ElMessage.error(errorMessage(e))}}
onMounted(async()=>{await Promise.all([load(),loadStores()])});
</script>
<template><div class="page"><div class="page-head"><div><h1 class="page-title">员工管理</h1><p class="page-subtitle">维护员工档案、所属门店和岗位角色</p></div><el-button type="primary" @click="open()">＋ 添加员工</el-button></div><section class="panel"><div class="toolbar"><el-input v-model="query.keyword" clearable placeholder="搜索姓名或手机号" style="width:240px" @keyup.enter="query.page=1;load()"/><el-select v-model="query.role" clearable placeholder="全部角色" style="width:140px"><el-option v-for="r in roles" :key="r" :label="roleLabels[r]" :value="r"/></el-select><el-select v-model="query.storeId" clearable placeholder="全部门店" style="width:160px"><el-option v-for="s in stores" :key="s.id" :label="s.name" :value="s.id"/></el-select><el-button @click="query.page=1;load()">查询</el-button></div><el-table v-loading="loading" :data="result.items"><el-table-column label="姓名" min-width="140"><template #default="s"><div class="employee"><i>{{s.row.name.slice(0,1)}}</i><b>{{s.row.name}}</b></div></template></el-table-column><el-table-column prop="phone" label="手机号" width="145"/><el-table-column label="门店" min-width="140"><template #default="s">{{s.row.store?.name||'未分配'}}</template></el-table-column><el-table-column label="角色" width="120"><template #default="s"><el-tag effect="plain">{{roleLabels[s.row.role as RoleCode]}}</el-tag></template></el-table-column><el-table-column label="状态" width="100"><template #default="s"><span class="status-dot" :class="{off:s.row.status==='DISABLED'}"/>{{s.row.status==='ACTIVE'?'启用':'停用'}}</template></el-table-column><el-table-column label="加入日期" width="130"><template #default="s">{{s.row.joinDate?.slice(0,10)||'—'}}</template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="s"><template v-if="s.row.role!=='OWNER'"><el-button link type="primary" @click="open(s.row)">编辑</el-button><el-button link type="danger" @click="remove(s.row)">删除</el-button></template><span v-else class="protected">受保护</span></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="query.page" v-model:page-size="query.pageSize" layout="total, prev, pager, next" :total="result.total" @change="load"/></div></section>
<el-dialog v-model="dialog" :title="editingId?'编辑员工':'添加员工'" width="560px"><el-form :model="form" label-position="top"><div class="form-grid"><el-form-item label="姓名" required><el-input v-model="form.name"/></el-form-item><el-form-item label="手机号" required><el-input v-model="form.phone"/></el-form-item><el-form-item label="所属门店"><el-select v-model="form.storeId" clearable style="width:100%"><el-option v-for="s in stores" :key="s.id" :label="s.name" :value="s.id"/></el-select></el-form-item><el-form-item label="角色" required><el-select v-model="form.role" style="width:100%"><el-option v-for="r in roles" :key="r" :label="roleLabels[r]" :value="r"/></el-select></el-form-item><el-form-item label="加入日期"><el-date-picker v-model="form.joinDate" type="date" value-format="YYYY-MM-DD" style="width:100%"/></el-form-item><el-form-item label="状态"><el-radio-group v-model="form.status"><el-radio value="ACTIVE">启用</el-radio><el-radio value="DISABLED">停用</el-radio></el-radio-group></el-form-item></div></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog></div></template>
<style scoped>.employee{display:flex;align-items:center;gap:10px}.employee i{width:30px;height:30px;display:grid;place-items:center;border-radius:8px;background:#e8f1ed;color:#315c4e;font-style:normal}.employee b{font-size:13px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 18px}.protected{font-size:12px;color:#9aa3af}</style>
