<script setup lang="ts">
import { onMounted,reactive,ref } from 'vue';import{ElMessage}from'element-plus';import api,{errorMessage}from'@/api/http';import type{Merchant,Paged}from'@/types';
const loading=ref(false),dialog=ref(false),saving=ref(false);const query=reactive({keyword:'',status:'',page:1,pageSize:10});const result=reactive<Paged<Merchant>>({items:[],total:0,page:1,pageSize:10});const form=reactive({name:'',merchantCode:'',contactName:'',contactPhone:'',plan:'TRIAL',expireAt:'',ownerUsername:'',ownerPassword:'',ownerName:'',ownerPhone:''});
const planLabels:Record<string,string>={TRIAL:'试用版',BASIC:'基础版',PROFESSIONAL:'专业版',ENTERPRISE:'企业版'};const statusLabels:Record<string,string>={ACTIVE:'正常',DISABLED:'停用',EXPIRED:'已过期'};
async function load(){loading.value=true;const params=Object.fromEntries(Object.entries(query).filter(([,value])=>value!==''));try{Object.assign(result,(await api.get('/merchants',{params})).data)}catch(e){ElMessage.error(errorMessage(e))}finally{loading.value=false}}
async function save(){saving.value=true;try{await api.post('/merchants',{...form,expireAt:form.expireAt||undefined});ElMessage.success('商家创建成功');dialog.value=false;await load()}catch(e){ElMessage.error(errorMessage(e))}finally{saving.value=false}}
async function toggle(row:Merchant){try{await api.patch(`/merchants/${row.id}`,{status:row.status==='ACTIVE'?'DISABLED':'ACTIVE'});ElMessage.success('状态已更新');await load()}catch(e){ElMessage.error(errorMessage(e))}}
onMounted(load);
</script>
<template><div class="page"><div class="page-head"><div><h1 class="page-title">商家管理</h1><p class="page-subtitle">创建与维护平台入驻商家</p></div><el-button type="primary" @click="dialog=true">＋ 创建商家</el-button></div><section class="panel"><div class="toolbar"><el-input v-model="query.keyword" clearable placeholder="搜索商家名称或编码" style="width:260px"/><el-select v-model="query.status" clearable placeholder="全部状态" style="width:140px"><el-option label="正常" value="ACTIVE"/><el-option label="停用" value="DISABLED"/><el-option label="已过期" value="EXPIRED"/></el-select><el-button @click="load">查询</el-button></div><el-table v-loading="loading" :data="result.items"><el-table-column prop="name" label="商家名称" min-width="180"/><el-table-column prop="merchantCode" label="商家编码" width="130"/><el-table-column label="套餐" width="120"><template #default="s">{{planLabels[s.row.plan]}}</template></el-table-column><el-table-column label="门店 / 员工" width="140"><template #default="s">{{s.row._count.stores}} / {{s.row._count.employees}}</template></el-table-column><el-table-column prop="contactPhone" label="联系电话" width="150"/><el-table-column label="状态" width="100"><template #default="s"><span class="status-dot" :class="{off:s.row.status!=='ACTIVE'}"/>{{statusLabels[s.row.status]}}</template></el-table-column><el-table-column label="操作" width="130"><template #default="s"><el-button link :type="s.row.status==='ACTIVE'?'danger':'primary'" @click="toggle(s.row)">{{s.row.status==='ACTIVE'?'停用':'启用'}}</el-button></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="query.page" :total="result.total" layout="total, prev, pager, next" @change="load"/></div></section>
<el-dialog v-model="dialog" title="创建旅拍商家" width="620px"><el-form :model="form" label-position="top"><div class="grid"><el-form-item label="商家名称" required><el-input v-model="form.name"/></el-form-item><el-form-item label="商家编码" required><el-input v-model="form.merchantCode" placeholder="大写字母或数字"/></el-form-item><el-form-item label="联系人"><el-input v-model="form.contactName"/></el-form-item><el-form-item label="联系电话"><el-input v-model="form.contactPhone"/></el-form-item><el-form-item label="套餐"><el-select v-model="form.plan" style="width:100%"><el-option label="试用版" value="TRIAL"/><el-option label="基础版" value="BASIC"/><el-option label="专业版" value="PROFESSIONAL"/><el-option label="企业版" value="ENTERPRISE"/></el-select></el-form-item><el-form-item label="到期时间"><el-date-picker v-model="form.expireAt" value-format="YYYY-MM-DD" style="width:100%"/></el-form-item></div><el-divider content-position="left">老板账号</el-divider><div class="grid"><el-form-item label="老板姓名" required><el-input v-model="form.ownerName"/></el-form-item><el-form-item label="老板手机号" required><el-input v-model="form.ownerPhone"/></el-form-item><el-form-item label="登录账号" required><el-input v-model="form.ownerUsername"/></el-form-item><el-form-item label="初始密码" required><el-input v-model="form.ownerPassword" type="password" show-password/></el-form-item></div></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">创建</el-button></template></el-dialog></div></template>
<style scoped>.grid{display:grid;grid-template-columns:1fr 1fr;gap:0 18px}</style>
