<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { ElMessage } from 'element-plus';
import api,{errorMessage} from '@/api/http';
import { useAuthStore } from '@/stores/auth';
import type { Employee, Order, OrderStatus, Paged, ServiceRecord, ServiceStage, Store } from '@/types';

const auth=useAuthStore();
const loading=ref(false),createDialog=ref(false),replaceDialog=ref(false),addDialog=ref(false),saving=ref(false);
const result=reactive<Paged<Order>>({items:[],total:0,page:1,pageSize:20});
const query=reactive({keyword:'',status:'' as OrderStatus|'',page:1,pageSize:20});
const stores=ref<Store[]>([]),eligible=ref<Employee[]>([]),activeOrder=ref<Order|null>(null),activeStage=ref<ServiceStage>('MAKEUP');
const createForm=reactive({customerName:'',customerPhone:'',storeId:'',packageName:'',appointmentAt:'',notes:''});
const replaceForm=reactive({newEmployeeId:'',reason:''});
const addForm=reactive({name:'',quantity:1,unitAmount:0,description:''});
const statusLabels:Record<OrderStatus,string>={PENDING_CONFIRMATION:'待门店确认',WAITING_MAKEUP:'待化妆认领',MAKEUP_IN_PROGRESS:'化妆进行中',WAITING_PHOTOGRAPHY:'待摄影认领',PHOTOGRAPHY_IN_PROGRESS:'摄影进行中',WAITING_SELECTION:'待客户确认选片',WAITING_RETOUCH:'待修片',COMPLETED:'已完成',CANCELLED:'已取消'};
const stageLabels:Record<ServiceStage,string>={MAKEUP:'化妆',PHOTOGRAPHY:'摄影'};
const canCreate=computed(()=>['OWNER','MANAGER','RECEPTION'].includes(auth.profile?.role??''));
const clientCreateUrl=computed(()=>`${globalThis.location.origin}/client/create/${auth.profile?.merchant?.merchantCode??''}`);

async function load(){loading.value=true;try{const params=Object.fromEntries(Object.entries(query).filter(([,v])=>v!==''));Object.assign(result,(await api.get<Paged<Order>>('/orders',{params})).data)}catch(e){ElMessage.error(errorMessage(e))}finally{loading.value=false}}
async function loadStores(){if(canCreate.value)stores.value=(await api.get<Paged<Store>>('/stores',{params:{pageSize:100,status:'ACTIVE'}})).data.items}
async function action(order:Order,path:string,stage?:ServiceStage){try{await api.post(`/orders/${order.id}/${path}`,stage?{stage}:{});ElMessage.success('操作成功');await load()}catch(e){ElMessage.error(errorMessage(e))}}
async function confirm(order:Order){try{await api.patch(`/orders/${order.id}/confirm`);ElMessage.success('订单已确认，等待化妆师认领');await load()}catch(e){ElMessage.error(errorMessage(e))}}
function current(order:Order,stage:ServiceStage){return order.serviceRecords.find(r=>r.stage===stage&&r.isCurrent)}
function canClaim(order:Order,stage:ServiceStage){return (stage==='MAKEUP'&&auth.profile?.role==='MAKEUP'&&order.status==='WAITING_MAKEUP'&&!current(order,stage))||(stage==='PHOTOGRAPHY'&&auth.profile?.role==='PHOTOGRAPHER'&&order.status==='WAITING_PHOTOGRAPHY'&&!current(order,stage))}
function canOperate(record?:ServiceRecord){return Boolean(record&&(auth.profile?.role==='OWNER'||auth.profile?.role==='MANAGER'||record.employeeId===auth.profile?.employee?.id))}
function openCreate(){Object.assign(createForm,{customerName:'',customerPhone:'',storeId:stores.value[0]?.id??'',packageName:'',appointmentAt:'',notes:''});createDialog.value=true}
async function saveOrder(){if(!createForm.customerName||!createForm.customerPhone||!createForm.storeId){ElMessage.warning('请填写客户、手机号和门店');return}saving.value=true;try{await api.post('/orders',{...createForm,appointmentAt:createForm.appointmentAt||undefined,packageName:createForm.packageName||undefined,notes:createForm.notes||undefined});ElMessage.success('订单已创建');createDialog.value=false;await load()}catch(e){ElMessage.error(errorMessage(e))}finally{saving.value=false}}
async function openReplace(order:Order,stage:ServiceStage){activeOrder.value=order;activeStage.value=stage;Object.assign(replaceForm,{newEmployeeId:'',reason:''});eligible.value=(await api.get<Employee[]>('/orders/eligible-employees',{params:{stage}})).data.filter(e=>e.id!==current(order,stage)?.employeeId);replaceDialog.value=true}
async function saveReplace(){if(!activeOrder.value||!replaceForm.newEmployeeId||!replaceForm.reason){ElMessage.warning('请选择接替员工并填写原因');return}saving.value=true;try{await api.post(`/orders/${activeOrder.value.id}/replace`,{stage:activeStage.value,...replaceForm});ElMessage.success('换人成功，原服务记录已保留');replaceDialog.value=false;await load()}catch(e){ElMessage.error(errorMessage(e))}finally{saving.value=false}}
function openAdd(order:Order,stage:ServiceStage){activeOrder.value=order;activeStage.value=stage;Object.assign(addForm,{name:'',quantity:1,unitAmount:0,description:''});addDialog.value=true}
async function saveAdd(){if(!activeOrder.value||!addForm.name){ElMessage.warning('请填写服务名称');return}saving.value=true;try{await api.post(`/orders/${activeOrder.value.id}/value-added`,{stage:activeStage.value,...addForm});ElMessage.success('已提交，等待客户确认');addDialog.value=false;await load()}catch(e){ElMessage.error(errorMessage(e))}finally{saving.value=false}}
function clientUrl(order:Order){return `${globalThis.location.origin}/client/order/${order.accessToken}`}
async function copy(text:string){await globalThis.navigator.clipboard.writeText(text);ElMessage.success('链接已复制')}
function openClient(order:Order){globalThis.open(clientUrl(order),'_blank')}
onMounted(async()=>{await Promise.all([load(),loadStores()])});
</script>

<template><div class="page"><div class="page-head"><div><h1 class="page-title">{{canCreate?'服务订单':'我的服务台'}}</h1><p class="page-subtitle">严格按照先化妆、后摄影流转，员工自主认领并记录增值服务</p></div><div class="head-actions"><el-button v-if="canCreate" @click="copy(clientCreateUrl)">复制客户扫码建单链接</el-button><el-button v-if="canCreate" type="primary" @click="openCreate">＋ 创建订单</el-button></div></div>
<section class="panel"><div class="toolbar"><el-input v-model="query.keyword" clearable placeholder="订单号、客户或手机号" style="width:260px" @keyup.enter="load"/><el-select v-model="query.status" clearable placeholder="全部状态" style="width:170px"><el-option v-for="(label,key) in statusLabels" :key="key" :label="label" :value="key"/></el-select><el-button @click="query.page=1;load()">查询</el-button></div>
<div v-loading="loading" class="order-list"><article v-for="order in result.items" :key="order.id" class="order-card"><div class="order-main"><div class="order-top"><div><b>{{order.customer.name}}</b><span>{{order.customer.phone}}</span><small>{{order.orderNo}}</small></div><el-tag effect="plain">{{statusLabels[order.status]}}</el-tag></div><div class="meta"><span>门店：{{order.store.name}}</span><span>套餐：{{order.packageName||'未填写'}}</span><span>预约：{{order.appointmentAt?.slice(0,16).replace('T',' ')||'待确定'}}</span></div>
<div class="flow"><div :class="{done:current(order,'MAKEUP')?.status==='COMPLETED',active:['WAITING_MAKEUP','MAKEUP_IN_PROGRESS'].includes(order.status)}"><i>1</i><p>化妆服务<small>{{current(order,'MAKEUP')?.employee.name||'等待认领'}}</small></p></div><span>→</span><div :class="{done:current(order,'PHOTOGRAPHY')?.status==='COMPLETED',active:['WAITING_PHOTOGRAPHY','PHOTOGRAPHY_IN_PROGRESS'].includes(order.status)}"><i>2</i><p>摄影服务<small>{{current(order,'PHOTOGRAPHY')?.employee.name||'化妆完成后开放'}}</small></p></div><span>→</span><div :class="{active:order.status==='WAITING_SELECTION',done:order.status==='WAITING_RETOUCH'}"><i>3</i><p>外部选片<small>{{order.status==='WAITING_SELECTION'?'等待客户确认':order.status==='WAITING_RETOUCH'?'客户已确认':'尚未开始'}}</small></p></div></div>
<div v-if="order.valueAddedServices.length" class="add-summary"><b>增值服务</b><span v-for="item in order.valueAddedServices" :key="item.id">{{item.name}} ¥{{item.totalAmount}} · {{item.status==='CONFIRMED'?'客户已确认':item.status==='DISPUTED'?'客户有异议':'待确认'}}</span></div></div>
<aside class="order-actions"><el-button v-if="order.status==='PENDING_CONFIRMATION'&&canCreate" type="primary" @click="confirm(order)">确认订单</el-button><template v-for="stage in (['MAKEUP','PHOTOGRAPHY'] as ServiceStage[])" :key="stage"><el-button v-if="canClaim(order,stage)" type="primary" @click="action(order,'claim',stage)">认领{{stageLabels[stage]}}</el-button><template v-if="canOperate(current(order,stage))"><el-button v-if="current(order,stage)?.status==='CLAIMED'" @click="action(order,'start',stage)">开始{{stageLabels[stage]}}</el-button><el-button v-if="current(order,stage)?.status==='IN_PROGRESS'" type="success" @click="action(order,'complete',stage)">完成{{stageLabels[stage]}}</el-button><el-button v-if="['CLAIMED','IN_PROGRESS'].includes(current(order,stage)?.status||'')" @click="openAdd(order,stage)">＋ 增值服务</el-button><el-button v-if="['CLAIMED','IN_PROGRESS'].includes(current(order,stage)?.status||'')" @click="openReplace(order,stage)">换人</el-button></template></template><el-button link @click="openClient(order)">客户确认页</el-button></aside></article><el-empty v-if="!loading&&!result.items.length" description="暂无订单"/></div><div class="pagination"><el-pagination v-model:current-page="query.page" layout="total, prev, pager, next" :total="result.total" @change="load"/></div></section>
<el-dialog v-model="createDialog" title="创建客户订单" width="620px"><el-form label-position="top"><div class="form-grid"><el-form-item label="客户姓名" required><el-input v-model="createForm.customerName"/></el-form-item><el-form-item label="手机号" required><el-input v-model="createForm.customerPhone"/></el-form-item><el-form-item label="服务门店" required><el-select v-model="createForm.storeId" style="width:100%"><el-option v-for="s in stores" :key="s.id" :label="s.name" :value="s.id"/></el-select></el-form-item><el-form-item label="预约时间"><el-date-picker v-model="createForm.appointmentAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" style="width:100%"/></el-form-item><el-form-item label="套餐名称"><el-input v-model="createForm.packageName"/></el-form-item><el-form-item label="备注"><el-input v-model="createForm.notes"/></el-form-item></div></el-form><template #footer><el-button @click="createDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveOrder">创建</el-button></template></el-dialog>
<el-dialog v-model="replaceDialog" :title="`${stageLabels[activeStage]}服务换人`" width="500px"><el-alert title="原员工的服务记录不会删除，方便后续审核提成归属" type="info" :closable="false"/><el-form label-position="top" style="margin-top:18px"><el-form-item label="接替员工" required><el-select v-model="replaceForm.newEmployeeId" style="width:100%"><el-option v-for="e in eligible" :key="e.id" :label="e.name" :value="e.id"/></el-select></el-form-item><el-form-item label="换人原因" required><el-input v-model="replaceForm.reason" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="replaceDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveReplace">确认换人</el-button></template></el-dialog>
<el-dialog v-model="addDialog" :title="`添加${stageLabels[activeStage]}增值服务`" width="540px"><el-form label-position="top"><el-form-item label="服务名称" required><el-input v-model="addForm.name" placeholder="例如：造型增加、拍摄场景升级"/></el-form-item><div class="form-grid"><el-form-item label="数量"><el-input-number v-model="addForm.quantity" :min="1" :max="99"/></el-form-item><el-form-item label="单价"><el-input-number v-model="addForm.unitAmount" :min="0" :precision="2"/></el-form-item></div><el-form-item label="服务说明"><el-input v-model="addForm.description" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="addDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveAdd">提交客户确认</el-button></template></el-dialog></div></template>

<style scoped>.head-actions{display:flex;gap:10px}.order-list{display:grid;gap:14px}.order-card{display:flex;border:1px solid #e8ebef;border-radius:12px;padding:18px;background:#fff}.order-main{flex:1;min-width:0}.order-top{display:flex;justify-content:space-between}.order-top>div{display:flex;align-items:center;gap:12px}.order-top b{font-size:17px}.order-top span{color:#687487;font-size:13px}.order-top small{color:#a0a8b3}.meta{display:flex;gap:26px;margin:14px 0;color:#687487;font-size:12px}.flow{display:flex;align-items:center;gap:12px;background:#f8fafb;border-radius:10px;padding:13px 16px}.flow>div{display:flex;align-items:center;gap:9px;min-width:150px;color:#a0a8b3}.flow>div i{font-style:normal;width:26px;height:26px;border-radius:50%;background:#e8ebef;display:grid;place-items:center;font-size:12px}.flow>div.active,.flow>div.done{color:#315c4e}.flow>div.active i{background:#315c4e;color:#fff}.flow>div.done i{background:#dcebe4;color:#315c4e}.flow p{margin:0;font-size:13px;font-weight:600}.flow small{display:block;font-weight:400;margin-top:3px}.flow>span{color:#c2c8d0}.order-actions{width:145px;border-left:1px solid #edf0f3;margin-left:18px;padding-left:18px;display:flex;flex-direction:column;gap:8px;justify-content:center}.order-actions .el-button{margin-left:0}.add-summary{display:flex;gap:10px;align-items:center;margin-top:12px;font-size:12px}.add-summary span{background:#fff7e7;color:#8a6321;padding:5px 8px;border-radius:6px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 18px}</style>
