<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import api, { errorMessage } from '@/api/http';
import type { Paged, Store } from '@/types';
const loading=ref(false), dialog=ref(false), saving=ref(false), editingId=ref('');
const query=reactive({keyword:'',status:'',page:1,pageSize:10}); const result=reactive<Paged<Store>>({items:[],total:0,page:1,pageSize:10});
const form=reactive({name:'',address:'',contactPhone:'',status:'ACTIVE' as Store['status']});
async function load(){loading.value=true;const params=Object.fromEntries(Object.entries(query).filter(([,value])=>value!==''));try{Object.assign(result,(await api.get<Paged<Store>>('/stores',{params})).data)}catch(e){ElMessage.error(errorMessage(e))}finally{loading.value=false}}
function open(item?:Store){editingId.value=item?.id??'';Object.assign(form,{name:item?.name??'',address:item?.address??'',contactPhone:item?.contactPhone??'',status:item?.status??'ACTIVE'});dialog.value=true}
async function save(){if(!form.name){ElMessage.warning('请输入门店名称');return}saving.value=true;try{if(editingId.value){await api.patch(`/stores/${editingId.value}`,form)}else{await api.post('/stores',form)}ElMessage.success(editingId.value?'修改成功':'新增成功');dialog.value=false;await load()}catch(e){ElMessage.error(errorMessage(e))}finally{saving.value=false}}
async function remove(item:Store){await ElMessageBox.confirm(`确认删除门店“${item.name}”？删除后不会物理清除数据。`,'删除门店',{type:'warning'});try{await api.delete(`/stores/${item.id}`);ElMessage.success('已删除');await load()}catch(e){ElMessage.error(errorMessage(e))}}
onMounted(load);
</script>
<template><div class="page"><div class="page-head"><div><h1 class="page-title">门店管理</h1><p class="page-subtitle">管理商家的线下服务门店与联系方式</p></div><el-button type="primary" @click="open()">＋ 新增门店</el-button></div><section class="panel"><div class="toolbar"><el-input v-model="query.keyword" clearable placeholder="搜索门店名称或地址" style="width:260px" @keyup.enter="query.page=1;load()"/><el-select v-model="query.status" clearable placeholder="全部状态" style="width:130px"><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="DISABLED"/></el-select><el-button @click="query.page=1;load()">查询</el-button></div><el-table v-loading="loading" :data="result.items"><el-table-column prop="name" label="门店名称" min-width="150"/><el-table-column prop="address" label="地址" min-width="250"><template #default="s">{{s.row.address||'—'}}</template></el-table-column><el-table-column prop="contactPhone" label="联系电话" width="150"><template #default="s">{{s.row.contactPhone||'—'}}</template></el-table-column><el-table-column label="状态" width="110"><template #default="s"><span class="status-dot" :class="{off:s.row.status==='DISABLED'}"/>{{s.row.status==='ACTIVE'?'启用':'停用'}}</template></el-table-column><el-table-column label="创建时间" width="180"><template #default="s">{{new Date(s.row.createdAt).toLocaleString('zh-CN')}}</template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="s"><el-button link type="primary" @click="open(s.row)">编辑</el-button><el-button link type="danger" @click="remove(s.row)">删除</el-button></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="query.page" v-model:page-size="query.pageSize" layout="total, prev, pager, next" :total="result.total" @change="load"/></div></section>
<el-dialog v-model="dialog" :title="editingId?'编辑门店':'新增门店'" width="520px"><el-form :model="form" label-position="top"><el-form-item label="门店名称" required><el-input v-model="form.name" placeholder="例如：大召店"/></el-form-item><el-form-item label="门店地址"><el-input v-model="form.address" placeholder="请输入详细地址"/></el-form-item><el-form-item label="联系电话"><el-input v-model="form.contactPhone" placeholder="手机号或座机"/></el-form-item><el-form-item label="状态"><el-radio-group v-model="form.status"><el-radio value="ACTIVE">启用</el-radio><el-radio value="DISABLED">停用</el-radio></el-radio-group></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog></div></template>
